### ISSUE TITLE
유저 개인 설정 섹션에 소셜로그인 메뉴가 추가되지 않습니다.

### ISSUE THREAD

**Issue by anakkadde** [xpressengine/plugin-social_login#1]
.env에 5개중 페이스북과 네이버에 앱 키와 시크릿 키 넣었고
플러그인도 제대로 킨상태입니다. 네, 근데 안되요! 
에러 뜬다거나 하는게 아니라 문장 그대로 아주 메뉴가 추가되지 않습니다!

으헝헝

**Comment by khongchi** [comment]
메뉴가 추가되지 않는다는게 페이스북/네이버 등등의 로그인 버튼이 안 보인다는 말씀이시죠?
일단 `사이트관리>회원>설정>스킨설정`에서 인증 스킨을 소셜로그인 스킨으로 변경하셔야 합니다.

스킨 변경에 대한 안내가 부족했던 것 같습니다. 곧 보완하겠습니다.

**Comment by anakkadde** [comment]
아뇨 로그인 버튼 말고 회원 개인 설정 란 말하는거에요
로그인 후 사용자 아이콘 누르고 뜨는 드롭메뉴중에 나오는 개인 설정 메뉴 말이에요

**Comment by khongchi** [comment]
그부분은 오류가 있네요. dev4와 함께 수정하겠습니다.

**Comment by khongchi** [comment]
급하시다면 아래와 같이 패치해보세요.

plugins/social_login/plugin.php:65

~~`'member/settings/section',`~~
`'user/settings/section',`

**Comment by anakkadde** [comment]
감사합니다
