### ISSUE TITLE
소셜 로그인 사용할 때 facebook 오류

### ISSUE THREAD

**Issue by khongchi** [xpressengine/plugin-social_login#2]
https://xpressengine.io/qna/%EC%86%8C%EC%85%9C-%EB%A1%9C%EA%B7%B8%EC%9D%B8%EC%9D%80-%EC%96%B4%EB%96%BB%EA%B2%8C

```
ErrorException in FacebookProvider.php line 90:

Undefined index: first_name
```
소셜 로그인 점검 필요

**Comment by khongchi** [comment]
페이스북에서 해당 계정의 `계정설정>이름`  first_name이 누락되어있거나 페이스북이 정보를 전달해주지 않는 것으로 판단됩니다.

**Comment by jaymepark** [comment]
17.01.29 현재도 동일한 오류가 발생하고 있는데요~ 혹시 해결된 이슈일까요?
