### ISSUE TITLE
소셜로그인 스킨 기본 로그인에서 로그인 유지 기능이 동작하지 않는 문제

### ISSUE THREAD

**Issue by woongbin** [xpressengine/plugin-social_login#23]
소셜 로그인 기본 스킨 변경 되면서 로그인 유지 기능 동작 안하는 문제 수정

**Comment by xharpenParksuhyeon** [comment]
https://github.com/xpressengine/plugin-social_login/issues/27#issue-919467234

해당 이슈에서 해결된 문제입니다.
